# This is a basic workflow to help you get started with Actions
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  # Pester test job
  pester-test:
    runs-on: ubuntu-18.04
    steps:
      # checkout
      - uses: actions/checkout@v2
      # Runs Pester all *.tests.ps1 scripts
      - name: Run Pester test for Windows
        run: |
          Write-Output "Run Pester $(Get-InstalledModule Pester | Select-Object -ExpandProperty Version) ..."
          $config = [PesterConfiguration]@{
              Run = @{
                  Path = './OSVersion.Tests/'
                  # TestExtension is default setting (.Tests.ps1)
              }
              Output = @{
                  Verbosity = 'Detailed'
              }
          }
          Invoke-Pester -Configuration $config
        shell: pwsh
